#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2023.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Jan 12 13:42:07 MST 2024
# SW Build 4029153 on Fri Oct 13 20:13:54 MDT 2023
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_w_icons_top_behav -key {Behavioral:sim_1:Functional:tb_w_icons_top} -tclbatch tb_w_icons_top.tcl -view /home/smaz-brn/project/ASIC-W-ICONS-FPGA/Cadence/w_icons/units/w_icons_top/fpga/vivado/project_1/tb_w_icons_top_behav.wcfg -log simulate.log"
xsim tb_w_icons_top_behav -key {Behavioral:sim_1:Functional:tb_w_icons_top} -tclbatch tb_w_icons_top.tcl -view /home/smaz-brn/project/ASIC-W-ICONS-FPGA/Cadence/w_icons/units/w_icons_top/fpga/vivado/project_1/tb_w_icons_top_behav.wcfg -log simulate.log

